server:
  port: 8084
http-client:
  type: httpClientApache
  host: http://localhost:8083
  login:
    username: str1k6r
    password: that'sME
html-parser:
  default-link: https://en.wikipedia.org/wiki/List_of_football_clubs_in_Spain
logging:
  level:
    root: INFO
